import React, { useEffect, useState } from "react"
import { FaMoneyBill } from 'react-icons/fa'
import { useLocation } from 'react-router-dom'
import styled from 'styled-components'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar/Navbar'
import { userRequest } from "../requestMethods"
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;



const Container = styled.div`
 background-color:#f0f0f0;
    width:100vw;
    height: 80vh;
    display: flex;
    flex-direction:column;
    align-items:center;
    justify-content:center;
`

const Wrapper = styled.div`
    width:50%;
    background-color:white;
    padding: 20px;
`

const InfoContainer = styled.div`
    margin:10px;
    display:flex;
    align-items:center;
`

const InfoText = styled.p`
    margin-left:24px;
`

const Table = styled.table`
    border-collapse: collapse;
    width: 100%;
`

const Tr = styled.tr``

const Th = styled.th`
    padding:10px;
    text-align:left;
    border-bottom: 2px solid #ddd;
`

const Td = styled.td`
    padding:10px;
    text-align:left;
    border-bottom: 1px solid #ddd;
`

const Button = styled.button`
    margin:20px 20px 20px 0;
    border:none;
    border-radius:4px;
    background-color: #6246ca;
    padding: 10px 40px;
    color:white;
    font-size:16px;
    cursor: pointer;

`

const PaySlip = () => {
    const location = useLocation();
    const id = location.pathname.split("/")[2];
    const [payslip, setPayslip] = useState([]);


    const format = (num) => {
        return parseInt(num).toFixed(2).toLocaleString('en-US');
    }

    const docDefinition = {

        content: [
            { text: 'Payslip', style: 'header' },
            { text: 'Company Name', style: 'subheader' },
            'Company Address',
            'ABN',
            'Phone Number',
            { text: ' ', fontSize: 70 },
            {
                style: 'tableExample',
                table: {
                    widths: [200, 300],
                    heights: 30,
                    body: [
                        [{ text: 'Item', style: 'tableHeader' }, { text: 'Details', style: 'tableHeader' }],
                        ['Emplpoyee', `${payslip.firstName} ${payslip.lastName}`],
                        ['Pay Date', `${payslip.payStartDate?.split("T")[0]}`],
                        ['Pay Frequency', `${payslip.payFrequency}`],
                        ['Annual Income', `$ ${format(payslip.annualSalary)}`],
                        ['Gross Income', `$ ${format(payslip.grossIncome)}`],
                        ['Income Tax', `$ ${format(payslip.tax)}`],
                        ['Net Income', `$ ${format(payslip.netIncome)}`],
                        ['Superannuation', `$ ${format(payslip.superannuation)}`],
                        [{ text: 'Pay Amount', style: 'tableHeader' }, { text: `$ ${format(payslip.pay)}`, style: 'tableHeader' }],
                    ]
                }

            },
            { text: ' ', fontSize: 70 },
            'Generated by EzPayslip Inc.',
        ],
        styles: {
            header: {
                fontSize: 18,
                bold: true,
                margin: [0, 0, 0, 10]
            },
            subheader: {
                fontSize: 16,
                bold: true,
                margin: [0, 10, 0, 5]
            },
            tableExample: {
                margin: [0, 5, 0, 15]
            },
            tableHeader: {
                bold: true,
                fontSize: 13,
                color: 'black'
            }
        },

    };



    const printToPdf = () => {
        pdfMake.createPdf(docDefinition).print();
    }

    const downloadToPdf = () => {
        pdfMake.createPdf(docDefinition).download();
    }

    useEffect(() => {
        const getOnePayslip = async () => {
            try {
                const res = await userRequest.get(`/payslip/${id}`);
                setPayslip(res.data);
            } catch { };
        }
        getOnePayslip();
    }, [id])



    return (
        <>
            <Navbar />
            <Container>
                <Wrapper>
                    <InfoContainer>
                        <FaMoneyBill size="30" />
                        <InfoText>Pay Slip for {payslip.firstName} {payslip.lastName}</InfoText>
                    </InfoContainer >
                    <Table>
                        <Tr>
                            <Th>Item</Th>
                            <Th>Employee Details</Th>
                        </Tr>
                        <Tr>
                            <Td>Employee</Td>
                            <Td>{payslip.firstName} {payslip.lastName}</Td>
                        </Tr>
                        <Tr>
                            <Td>Pay Date</Td>
                            <Td>{payslip.payStartDate?.split("T")[0]}</Td>
                        </Tr>
                        <Tr>
                            <Td>Pay Frequency</Td>
                            <Td>Monthly</Td>
                        </Tr>
                        <Tr>
                            <Td>Annual Income</Td>
                            <Td>$ {format(payslip.annualSalary)}</Td>
                        </Tr>
                        <Tr>
                            <Td>Gross Income</Td>
                            <Td>$ {format(payslip.grossIncome)}</Td>
                        </Tr>
                        <Tr>
                            <Td>Income Tax</Td>
                            <Td>$ {format(payslip.tax)}</Td>
                        </Tr>
                        <Tr>
                            <Td>Net Income</Td>
                            <Td>$ {format(payslip.netIncome)}</Td>
                        </Tr>
                        <Tr>
                            <Td>Super</Td>
                            <Td>$ {format(payslip.superannuation)}</Td>
                        </Tr>
                        <Tr>
                            <Td>Pay</Td>
                            <Td>$ {format(payslip.pay)}</Td>
                        </Tr>
                    </Table>
                    <Button onClick={printToPdf}>Print</Button>
                    <Button onClick={downloadToPdf}>Download</Button>
                </Wrapper>
            </Container>
            <Footer />
        </>
    )
}

export default PaySlip