import { format } from "./util";

export const docFormatter = (payslip) => {
  const name = `${payslip.firstName} ${payslip.lastName}`;
  const {
    payStartDate,
    annualSalary,
    grossIncome,
    tax,
    netIncome,
    superannuation,
    pay,
    payFrequency,
  } = payslip;

  return {
    content: [
      { text: "Payslip", style: "header" },
      { text: "Company Name", style: "subheader" },
      "Company Address",
      "ABN",
      "Phone Number",
      { text: " ", fontSize: 70 },
      {
        style: "tableExample",
        table: {
          widths: [200, 300],
          heights: 30,
          body: [
            [
              { text: "Item", style: "tableHeader" },
              { text: "Details", style: "tableHeader" },
            ],
            ["Emplpoyee", `${name}`],
            ["Pay Date", `${payStartDate?.split("T")[0]}`],
            ["Pay Frequency", `${payFrequency}`],
            ["Annual Income", `$ ${format(annualSalary)}`],
            ["Gross Income", `$ ${format(grossIncome)}`],
            ["Income Tax", `$ ${format(tax)}`],
            ["Net Income", `$ ${format(netIncome)}`],
            ["Superannuation", `$ ${format(superannuation)}`],
            [
              { text: "Pay Amount", style: "tableHeader" },
              { text: `$ ${format(pay)}`, style: "tableHeader" },
            ],
          ],
        },
      },
      { text: " ", fontSize: 70 },
      "Generated by EzPayslip Inc.",
    ],
    styles: {
      header: {
        fontSize: 18,
        bold: true,
        margin: [0, 0, 0, 10],
      },
      subheader: {
        fontSize: 16,
        bold: true,
        margin: [0, 10, 0, 5],
      },
      tableExample: {
        margin: [0, 5, 0, 15],
      },
      tableHeader: {
        bold: true,
        fontSize: 13,
        color: "black",
      },
    },
  };
};
